# Generated by Django 6.0.2 on 2026-02-03 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('mode', models.CharField(default='hybrid', max_length=10)),
                ('threshold', models.FloatField(default=0.75)),
                ('output_video', models.FileField(blank=True, null=True, upload_to='outputs/')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='forensics.forensiccase')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('log_type', models.CharField(default='info', max_length=10)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='forensics.forensiccase')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='evidence/refs/')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='forensics.forensiccase')),
            ],
        ),
    ]
