# Generated by Django 6.0.2 on 2026-02-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensiccase',
            name='suspect_clip',
            field=models.FileField(blank=True, null=True, upload_to='outputs/clips/'),
        ),
    ]
