# Generated by Django 6.0.2 on 2026-02-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0002_forensiccase_suspect_clip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forensiccase',
            name='suspect_clip',
        ),
    ]
