# Generated by Django 6.0.2 on 2026-02-05 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0003_remove_forensiccase_suspect_clip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspectSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('clip_file', models.FileField(upload_to='outputs/sightings/')),
                ('max_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='forensics.forensiccase')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
