# Generated by Django 6.0.2 on 2026-03-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0005_cctvstream_livetrackingsession_livealert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livealert',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='livetrackingsession',
            name='streams',
        ),
        migrations.RemoveField(
            model_name='livealert',
            name='session',
        ),
        migrations.RemoveField(
            model_name='livetrackingsession',
            name='case',
        ),
        migrations.RemoveField(
            model_name='suspectsighting',
            name='case',
        ),
        migrations.DeleteModel(
            name='CCTVStream',
        ),
        migrations.DeleteModel(
            name='LiveAlert',
        ),
        migrations.DeleteModel(
            name='LiveTrackingSession',
        ),
        migrations.DeleteModel(
            name='SuspectSighting',
        ),
    ]
