# Generated by Django 6.0.2 on 2026-03-11 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0006_remove_livealert_stream_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rtsp_url', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error')], default='IDLE', max_length=20)),
                ('last_frame_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveTrackingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(default='hybrid', max_length=10)),
                ('threshold', models.FloatField(default=0.55)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTING', 'Starting'), ('RUNNING', 'Running'), ('STOPPING', 'Stopping'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='STARTING', max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='forensics.forensiccase')),
                ('streams', models.ManyToManyField(blank=True, related_name='sessions', to='forensics.cctvstream')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frame_number', models.IntegerField(default=0)),
                ('confidence', models.FloatField()),
                ('track_id', models.IntegerField(default=-1)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='outputs/live_alerts/thumbs/')),
                ('clip_file', models.FileField(blank=True, null=True, upload_to='outputs/live_alerts/clips/')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='forensics.cctvstream')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='forensics.livetrackingsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SuspectSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('clip_file', models.FileField(upload_to='outputs/sightings/')),
                ('max_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='forensics.forensiccase')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
