# Generated by Django 6.0.4 on 2026-04-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0007_cctvstream_livetrackingsession_livealert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensiccase',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='outputs/reports/'),
        ),
    ]
