# Generated by Django 6.0.2 on 2026-05-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0008_forensiccase_report_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forensiccase',
            name='report_pdf',
        ),
    ]
