# Generated by Django 6.0.5 on 2026-06-01 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0009_remove_forensiccase_report_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('color', models.CharField(default='blue', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='dark', max_length=20)),
                ('notifications', models.BooleanField(default=True)),
                ('auto_save_streams', models.BooleanField(default=True)),
                ('default_detection_mode', models.CharField(default='hybrid', max_length=20)),
                ('default_threshold', models.FloatField(default=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
